name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Explore-GitHub-Actions:
    name: Run npm on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies And Build   
        run: npm ci
        run: npm run build
      - run: npm run test 
